name: Auto Release Workflow
on:
  push:
    tags:
      - "*"
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Generate build file
        run: npm run build
      - name: Create Release & Upload dist/
        uses: softprops/action-gh-release@v2
        with:
          files: dist/
